name: Packer Status Check
on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packer
        uses: hashicorp/setup-packer@v2
      - name: Create JSON File from Secret
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' | jq '.' > secret.json
      - name: Initialize Packer Plugins
        run: packer init -upgrade packer/
      - name: Packer Format Check
        run: packer fmt -check -diff -recursive packer/
      - name: Packer Validate
        run: |
          packer validate \
            -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            -var "ami_users=[\"000000000000\"]" \
            -var "credentials_file=secret.json" \
            packer/